# AWSテンプレートのバージョン。2022.1時点で唯一のバージョン
AWSTemplateFormatVersion: "2010-09-09"
# テンプレートの説明。実行時に表示されるので記載
Description: AWS-Study(create VPC only)

#プロジェクトごとに変数を定義(参考)
#Parameters:
#    ProjectCode:
#    Type: String
#    Default: itc109
#    Description: Project Code

# リソース定義
Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: aws-study-vpc

  # InternetGateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: aws-study-gw

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      #InternetGatewayId: !Ref InternetGateway

  # Subnet
  #oregon-2a
  PublicSubnet-2a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-2a
      CidrBlock: 10.1.1.0/24
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: aws-study-pubsubnet-2a
  #oregon-2c
  PublicSubnet-2c:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.1.2.0/24
      VpcId: !Ref VPC
      AvailabilityZone: us-west-2c
      Tags:
        - Key: Name
          Value: aws-study-pubsubnet-2c

  PrivateSubnet-2c:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.1.3.0/24
      VpcId: !Ref VPC
      AvailabilityZone: us-west-2c
      Tags:
        - Key: Name
          Value: aws-study-prisubnet-2c

  # RouteTable(PublicSubnet2a)
  # ルートテーブルの作成(VPCを指定)
  RouteTableForPublicSubnet-2a:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: RouteTableForPublicSubnet-2a
  # ルートの定義
  RouteForPublicSubnet-2a:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableForPublicSubnet-2a
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  # ルートテーブルとサブネットの紐付け
  AssocciateRouteTableForPublicSubnet-2a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForPublicSubnet-2a
      SubnetId: !Ref PublicSubnet-2a

  # RouteTable(PublicSubnet2c)
  # ルートテーブルの作成(VPCを指定)
  RouteTableForPublicSubnet-2c:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: RouteTableForPublicSubnet-2c
  # ルートの定義
  RouteForPublicSubnet-2a:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableForPublicSubnet-2c
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  # ルートテーブルとサブネットの紐付け
  AssocciateRouteTableForPublicSubnet-2a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableForPublicSubnet-2c
      SubnetId: !Ref PublicSubnet-2c


  # EIP for NatGateway
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  # NatGateway
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - NatGatewayEIP
          - AllocationId
      SubnetId: !Ref PublicSubnet-2a
      Tags:
        - Key: Name
          Value: NatGateway
